### ISSUE TITLE
With basic workflow I get 403 Resource not accessible by integration

### ISSUE THREAD

**Issue by 0GiS0** [github/evergreen#44]
Hi all 👋🏻

I tried to execute this workflow for my org:

```
name: Weekly dependabot checks
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

permissions: write-all  

jobs:
  evergreen:
    name: evergreen
    runs-on: ubuntu-latest

    steps:
      - name: Run evergreen action
        uses: github/evergreen@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: returngis
          # DRY_RUN: true
```

But I get the following error:

```
Checking returngis/tour-of-heroes-nuget
	Failed to enable Dependabot security updates.
Traceback (most recent call last):
  File "/action/workspace/evergreen.py", line 32[8](https://github.com/returngis/.github/actions/runs/7773680765/job/21197625687#step:3:9), in <module>
    main()  # pragma: no cover
    ^^^^^^
  File "/action/workspace/evergreen.py", line [12](https://github.com/returngis/.github/actions/runs/7773680765/job/21197625687#step:3:13)1, in main
    pull = commit_changes(
           ^^^^^^^^^^^^^^^
  File "/action/workspace/evergreen.py", line 2[14](https://github.com/returngis/.github/actions/runs/7773680765/job/21197625687#step:3:15), in commit_changes
    repo.create_ref(front_matter + branch_name, default_branch_commit)
  File "/usr/local/lib/python3.12/site-packages/github3/decorators.py", line 24, in auth_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/github3/repos/repo.py", line 1228, in create_ref
    json = self._json(self._post(url, data=data), 201)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/github3/models.py", line [16](https://github.com/returngis/.github/actions/runs/7773680765/job/21197625687#step:3:17)1, in _json
    raise exceptions.error_for(response)
github3.exceptions.ForbiddenError: 403 Resource not accessible by integration
```

If I enable `DRY_RUN`I can see all dependabot configurations for my repos but If I leave to false I get this error. I tried to put as permission `contents: write` and also `permissions: write-all` but I get the same error.

Any ideas? 

Thank you so much!

**Comment by zkoppert** [comment]
Yeah, I think what is going on here is that you are using the default `GITHUB_TOKEN` which is never going to have permissions to write in other repos. You need to generate a token that has write access for to repos in the whole org, and then store that secret in the repository and refer to it in your env. 

ie. 
```
name: Weekly dependabot checks
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

permissions: write-all  

jobs:
  evergreen:
    name: evergreen
    runs-on: ubuntu-latest

    steps:
      - name: Run evergreen action
        uses: github/evergreen@v1
        env:
          GH_TOKEN: ${{ secrets.ALL_ORG_TOKEN }}
          ORGANIZATION: returngis
          # DRY_RUN: true
```
where ALL_ORG_TOKEN is stored on the repo settings page. The relevant docs are here: 

- [Creating a token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic)
- [Creating a repository secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets)

**Comment by 0GiS0** [comment]
Thank you so much @zkoppert ! At the end I created a GitHub App and I used the action that @peter-murray made to get the token 😊

```
name: Weekly dependabot checks
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

env:
  ORGANIZATION: returngis

jobs:
  evergreen:
    name: evergreen
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub application token
        id: generate-token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
          organization: ${{ env.ORGANIZATION }}
          permissions: 'contents:write, pull_requests:write'
      - name: Run evergreen action
        uses: github/evergreen@v1.6.0
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          ORGANIZATION: ${{ env.ORGANIZATION }}
          #DRY_RUN: true
```
